package cg.tp01;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Josué
 */
public class MyJPanel extends javax.swing.JPanel {

    List<Pixel> pixels;
   
    private static Color color;
    
    /**
     * Creates new form MyJPanel
     */
    public MyJPanel() {
        initComponents();
        
        pixels = new ArrayList<>();
        color = new Color(0);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        pixels.stream().forEach((p) -> {
            p.draw(g);
        });
    }
    
    public void setPixel(int x, int y) {
        pixels.add(new Pixel(x, y, MyJPanel.color));
        repaint();
    }
    
    public void clear() {
        pixels.clear();
        repaint();
    }
    
    public void undo() {
        int index = pixels.size() - 1; 
        if (index >= 0) pixels.remove(index);
        repaint();
    }
    
    public static void setColor(Color color) {
        MyJPanel.color = color;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
    
